import { z } from 'zod'

export const aiResponseSchema = z.object({
  commentary: z.string().describe('Detailed commentary about the response or generated code.'),
  title: z.string().describe('Short title for the response. Max 3 words.'),
  description: z.string().describe('Short description of the response. Max 1 sentence.'),
  code: z.string().optional().describe('Code generated by the AI, if applicable. Only runnable code is allowed.'),
})

export type AiResponseSchema = z.infer<typeof aiResponseSchema>
